AIRPORT_CODES = {
    "london": ["LHR", "LGW", "STN", "LTN", "LCY"],
    "new york": ["JFK", "EWR", "LGA"],
    "beijing": ["PEK", "PKX"],
    "shanghai": ["PVG", "SHA"],
    "chengdu": ["CTU", "TFU"],
    "tokyo": ["HND", "NRT"],
    "osaka": ["KIX", "ITM"],
    "seoul": ["ICN", "GMP"],
    "taipei": ["TPE", "TSA"],
    "bangkok": ["BKK", "DMK"],
    "weihai": "WEH",
    "guangzhou": "CAN",
    "shenzhen": "SZX",
    "kunming": "KMG",
    "xian": "XIY",
    "chongqing": "CKG",
    "hangzhou": "HGH",
    "nanjing": "NKG",
    "xiamen": "XMN",
    "qingdao": "TAO",
    "wuhan": "WUH",
    "changsha": "CSX",
    "zhengzhou": "CGO",
    "fuzhou": "FOC",
    "guiyang": "KWE",
    "haikou": "HAK",
    "sanya": "SYX",
    "harbin": "HRB",
    "shenyang": "SHE",
    "taiyuan": "TYN",
    "nanning": "NNG",
    "guilin": "KWL",
    "hefei": "HFE",
    "urumqi": "URC",
    "lanzhou": "LHW",
    "shantou": "SWA",
    "zhuhai": "ZUH",
    "wuxi": "WUX",
    "ningbo": "NGB",
    "wenzhou": "WNZ",
    "singapore": "SIN",
    "nagoya": "NGO",
    "fukuoka": "FUK",
    "sapporo": "CTS",
    "okinawa": "OKA",
    "busan": "PUS",
    "jeju": "CJU",
    "hong kong": "HKG",
    "macau": "MFM",
    "kaohsiung": "KHH",
    "phuket": "HKT",
    "chiang mai": "CNX",
    "ho chi minh city": "SGN",
    "hanoi": "HAN",
    "da nang": "DAD",
    "kuala lumpur": "KUL",
    "penang": "PEN",
    "kota kinabalu": "BKI",
    "jakarta": "CGK",
    "bali": "DPS",
    "surabaya": "SUB",
    "manila": "MNL",
    "cebu": "CEB",
    "davao": "DVO",
    "phnom penh": "PNH",
    "siem reap": "REP",
    "yangon": "RGN",
    "vientiane": "VTE",
    "bandar seri begawan": "BWN",
    "delhi": "DEL",
    "mumbai": "BOM",
    "bangalore": "BLR",
    "chennai": "MAA",
    "hyderabad": "HYD",
    "kolkata": "CCU",
    "dhaka": "DAC",
    "kathmandu": "KTM",
    "colombo": "CMB",
    "male": "MLE",
    "karachi": "KHI",
    "islamabad": "ISB",
    "sydney": "SYD",
    "melbourne": "MEL",
    "brisbane": "BNE",
    "perth": "PER",
    "auckland": "AKL",
    "christchurch": "CHC"
}